/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

using System;

namespace O3DE
{
    /// <summary>
    /// Marks a class as an EBus handler. The O3DESharp source generator
    /// (O3DESharp.SourceGenerators) picks up this attribute at compile
    /// time and emits partial methods that wire the class into O3DE's
    /// BehaviorEBus dispatch surface.
    ///
    /// Typical use on top of a <see cref="ScriptComponent"/> subclass:
    /// <code>
    /// [EBus("TickBus")]
    /// public partial class MyTicker : ScriptComponent
    /// {
    ///     public override void OnCreate()
    ///     {
    ///         ConnectToTickBus();     // generated by the source generator
    ///     }
    ///
    ///     public override void OnDestroy()
    ///     {
    ///         DisconnectFromTickBus(); // generated
    ///     }
    ///
    ///     [EBusHandler("OnTick")]
    ///     private void HandleTick(float deltaTime, ScriptTimePoint time)
    ///     {
    ///         Debug.Log($"Tick! dt={deltaTime}");
    ///     }
    /// }
    /// </code>
    ///
    /// The class MUST be declared <c>partial</c> so the source generator
    /// can add the Connect/Disconnect methods to it. The generator emits
    /// a compile-time error if it isn't.
    ///
    /// For addressed buses (those with a non-empty AddressType in the
    /// reflection data, e.g. TransformNotificationBus addressed by
    /// EntityId), the Connect overload takes the address as a parameter:
    /// <c>ConnectToTransformNotificationBus(entityId)</c>. The generator
    /// determines whether to emit the addressed signature by looking at
    /// the BusName at codegen time against the project's reflection
    /// data dump - so the C# side of your script never has to know
    /// whether the bus is addressed or broadcast-only.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    public sealed class EBusAttribute : Attribute
    {
        /// <summary>
        /// Name of the EBus to connect to (must match what's reflected
        /// into BehaviorContext, e.g. "TickBus", "TransformNotificationBus",
        /// "MyGameNotificationBus").
        /// </summary>
        public string BusName { get; }

        /// <summary>
        /// Optional priority hint for handler ordering when the bus
        /// supports it. Higher priority = called earlier. Defaults to 0
        /// (engine default). Mirrors AZ::EBusHandlerPolicy::Single /
        /// Multiple / OrderedMultiple semantics on the C++ side.
        /// </summary>
        public int Priority { get; set; } = 0;

        public EBusAttribute(string busName)
        {
            BusName = busName ?? throw new ArgumentNullException(nameof(busName));
        }
    }

    /// <summary>
    /// Marks a method as the handler for a specific event on an EBus
    /// the containing class is registered for via <see cref="EBusAttribute"/>.
    /// The method signature must match the event's reflected parameters
    /// (with the same parameter types in the same order); the generator
    /// validates this at compile time against the project's reflection
    /// data dump and emits diagnostics if they don't match.
    ///
    /// The handler method can be public or private; the source generator
    /// reaches it via a generated dispatch shim that takes a JSON args
    /// envelope from the C++ side and unmarshals into typed parameters
    /// before invoking the user method.
    ///
    /// Example:
    /// <code>
    /// [EBus("TransformNotificationBus")]
    /// public partial class FollowParent : ScriptComponent
    /// {
    ///     [EBusHandler("OnTransformChanged")]
    ///     private void HandleTransformChanged(Transform local, Transform world)
    ///     {
    ///         Debug.Log($"transform changed: pos={world.Position}");
    ///     }
    /// }
    /// </code>
    /// </summary>
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
    public sealed class EBusHandlerAttribute : Attribute
    {
        /// <summary>
        /// Name of the event on the EBus this method handles. Must match
        /// what's reflected (e.g. "OnTick", "OnTransformChanged").
        /// </summary>
        public string EventName { get; }

        public EBusHandlerAttribute(string eventName)
        {
            EventName = eventName ?? throw new ArgumentNullException(nameof(eventName));
        }
    }
}
