#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
"""SP-0: prove that deleting the vendored gem copy is lossless.

The engine fork contains a vendored copy of this gem at Gems/O3DESharp that
drifted (pinned 109 commits back, with uncommitted local edits). Before that
copy is deleted, every file in it must be shown to be either identical to this
repo, superseded by this repo, or explicitly allow-listed as already rescued.

Line endings are normalized before comparison: the vendored copy is largely
CRLF and this repo is largely LF, so a raw byte compare reports ~100% of lines
as different and hides the real signal.

Usage:
    python Tools/sp0_verify_divergence.py <vendored_root> <repo_root> [-o manifest.md]

Exit code 0 = gate passed (deletion approved), 1 = gate blocked.
"""

import argparse
import sys
from pathlib import Path

# Directories that never carry source of record.
IGNORED_DIR_NAMES = {
    ".git", ".vs", ".vscode", "bin", "obj", "build", "Cache",
    "_deps", "node_modules", "__pycache__", ".worktrees",
    # Tool caches. These must be ignored or transient files (e.g.
    # .pytest_cache/v/cache/lastfailed) leak into the committed manifest and
    # make the audit trail non-reproducible - its counts would shift between
    # runs depending on what tests were last executed in either tree.
    ".pytest_cache", ".mypy_cache", ".ruff_cache", ".tox",
}

# The only files permitted to exist solely in the vendored copy.
# The nine source files were rescued verbatim to branch
# feat/1b-native-trampoline-rescue (commit 8a00627, pushed) and quarantined
# under Rescued/1b-native-trampoline/. UpgradeLog.htm is Visual Studio junk.
ALLOWED_ONLY_IN_VENDORED = {
    "Code/Source/Scripting/CoralNativeThunkHost.cpp",
    "Code/Source/Scripting/CoralNativeThunkHost.h",
    "Code/Source/Scripting/Reflection/BindingRegistry.cpp",
    "Code/Source/Scripting/Reflection/BindingRegistry.h",
    "Code/Source/Scripting/Reflection/NativeBindingManifest.cpp",
    "Code/Source/Scripting/Reflection/NativeBindingManifest.h",
    "Code/Tools/BindingGenerator/O3DESharp.BindingGenerator/Configuration/NativeBindingManifestSchema.cs",
    "Code/Tools/BindingGenerator/O3DESharp.BindingGenerator/Generation/NativeBindingGenerator.cs",
    "Code/Tools/BindingGenerator/O3DESharp.BindingGenerator/Parsing/ReflectionCallSiteParser.cs",
    "UpgradeLog.htm",
}


def normalize(data: bytes) -> bytes:
    """Collapse CRLF to LF so line-ending style is not treated as divergence."""
    return data.replace(b"\r\n", b"\n")


def _iter_files(root: Path):
    """Yield forward-slash relative paths of every non-ignored file under root."""
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if any(part in IGNORED_DIR_NAMES for part in rel.parts):
            continue
        yield rel.as_posix()


def classify(vendored_root: Path, repo_root: Path) -> dict:
    """Classify every vendored file as identical / differs / only_in_vendored."""
    vendored_root, repo_root = Path(vendored_root), Path(repo_root)
    identical, differs, only_in_vendored = [], [], []

    for rel in _iter_files(vendored_root):
        counterpart = repo_root / rel
        if not counterpart.is_file():
            only_in_vendored.append(rel)
            continue
        a = normalize((vendored_root / rel).read_bytes())
        b = normalize(counterpart.read_bytes())
        (identical if a == b else differs).append(rel)

    return {
        "identical": sorted(identical),
        "differs": sorted(differs),
        "only_in_vendored": sorted(only_in_vendored),
    }


def gate(result: dict) -> list:
    """Return vendored-only paths that are NOT allow-listed. Empty list = pass."""
    return sorted(set(result["only_in_vendored"]) - ALLOWED_ONLY_IN_VENDORED)


def render_manifest(result: dict, violations: list) -> str:
    """Render the committed audit trail."""
    verdict = "DELETION BLOCKED" if violations else "DELETION APPROVED"
    lines = [
        "# SP-0 Divergence Manifest",
        "",
        "Generated by `Tools/sp0_verify_divergence.py`. This is the audit trail",
        "justifying deletion of the vendored gem copy from the engine fork.",
        "",
        f"**Verdict: {verdict}**",
        "",
        "| Category | Count |",
        "|---|---|",
        f"| Identical to this repo (line-ending normalized) | {len(result['identical'])} |",
        f"| Differs (this repo authoritative) | {len(result['differs'])} |",
        f"| Exists only in the vendored copy | {len(result['only_in_vendored'])} |",
        "",
    ]

    if violations:
        lines += [
            "## Gate violations",
            "",
            "These files exist only in the vendored copy and are NOT allow-listed.",
            "**Do not delete the vendored copy.** Each must be rescued or explicitly discarded.",
            "",
        ] + [f"- `{p}`" for p in violations] + [""]
    else:
        lines += [
            "## Gate",
            "",
            "Every vendored-only file is allow-listed: the nine 1B sources rescued to",
            "`feat/1b-native-trampoline-rescue` (`8a00627`) plus `UpgradeLog.htm` (VS junk).",
            "Deletion is lossless.",
            "",
        ]

    lines += ["## Files existing only in the vendored copy", ""]
    lines += [f"- `{p}`" for p in result["only_in_vendored"]] or ["- (none)"]
    lines += ["", "## Files differing (this repo is authoritative)", ""]
    lines += [f"- `{p}`" for p in result["differs"]] or ["- (none)"]
    lines += [""]
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vendored_root")
    parser.add_argument("repo_root")
    parser.add_argument("-o", "--output", default=None)
    args = parser.parse_args(argv)

    result = classify(Path(args.vendored_root), Path(args.repo_root))
    violations = gate(result)
    manifest = render_manifest(result, violations)

    if args.output:
        Path(args.output).write_text(manifest, encoding="utf-8")

    print(manifest)
    return 1 if violations else 0


if __name__ == "__main__":
    sys.exit(main())
