/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// BehaviorContextReflector - Extracts and caches metadata from O3DE's BehaviorContext
    /// </summary>
    public class BehaviorContextReflector
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.BehaviorContextReflector_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.BehaviorContextReflector_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.BehaviorContextReflector_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.BehaviorContextReflector_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.BehaviorContextReflector_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.BehaviorContextReflector_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.BehaviorContextReflector_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.BehaviorContextReflector_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.BehaviorContextReflector_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.BehaviorContextReflector_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.BehaviorContextReflector_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.BehaviorContextReflector_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.BehaviorContextReflector_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.BehaviorContextReflector_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.BehaviorContextReflector_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.BehaviorContextReflector_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.BehaviorContextReflector_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.BehaviorContextReflector_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.BehaviorContextReflector_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.BehaviorContextReflector_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.BehaviorContextReflector_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.BehaviorContextReflector_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.BehaviorContextReflector_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.BehaviorContextReflector_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.BehaviorContextReflector_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.BehaviorContextReflector_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.BehaviorContextReflector_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.BehaviorContextReflector_operator delete[](/* this pointer */, p, size, align);
        }

        /// <summary>
        /// Reflects all types from the given BehaviorContext
        /// </summary>
        /// <param name="context"></param>
        public unsafe void ReflectFromContext(IntPtr context)
        {
            InternalCalls.BehaviorContextReflector_ReflectFromContext(/* this pointer */, context);
        }

        /// <summary>
        /// Clear all cached reflection data
        /// </summary>
        public unsafe void Clear()
        {
            InternalCalls.BehaviorContextReflector_Clear(/* this pointer */);
        }

        /// <summary>
        /// Get all reflected class names
        /// </summary>
        public unsafe string> GetClassNames()
        {
            return InternalCalls.BehaviorContextReflector_GetClassNames(/* this pointer */);
        }

        /// <summary>
        /// Get a reflected class by name
        /// </summary>
        /// <param name="className"></param>
        public unsafe IntPtr GetClass(string className)
        {
            return InternalCalls.BehaviorContextReflector_GetClass(/* this pointer */, className);
        }

        /// <summary>
        /// Get all reflected EBus names
        /// </summary>
        public unsafe string> GetEBusNames()
        {
            return InternalCalls.BehaviorContextReflector_GetEBusNames(/* this pointer */);
        }

        /// <summary>
        /// Get a reflected EBus by name
        /// </summary>
        /// <param name="busName"></param>
        public unsafe IntPtr GetEBus(string busName)
        {
            return InternalCalls.BehaviorContextReflector_GetEBus(/* this pointer */, busName);
        }

        /// <summary>
        /// Get all global methods (not part of any class)
        /// </summary>
        public unsafe vector<ReflectedMethod> GetGlobalMethods()
        {
            return InternalCalls.BehaviorContextReflector_GetGlobalMethods(/* this pointer */);
        }

        /// <summary>
        /// Get all global properties
        /// </summary>
        public unsafe vector<ReflectedProperty> GetGlobalProperties()
        {
            return InternalCalls.BehaviorContextReflector_GetGlobalProperties(/* this pointer */);
        }

        /// <summary>
        /// Check if a class is reflected
        /// </summary>
        /// <param name="className"></param>
        public unsafe bool HasClass(string className)
        {
            return InternalCalls.BehaviorContextReflector_HasClass(/* this pointer */, className);
        }

        /// <summary>
        /// Check if an EBus is reflected
        /// </summary>
        /// <param name="busName"></param>
        public unsafe bool HasEBus(string busName)
        {
            return InternalCalls.BehaviorContextReflector_HasEBus(/* this pointer */, busName);
        }

        /// <summary>
        /// Get classes that match a filter (e.g., category, module)
        /// </summary>
        /// <param name="category"></param>
        /// <param name="includeDeprecated"></param>
        public unsafe vector<const ReflectedClass *> GetClassesByCategory(string category, bool includeDeprecated)
        {
            return InternalCalls.BehaviorContextReflector_GetClassesByCategory(/* this pointer */, category, includeDeprecated);
        }

        /// <summary>
        /// Get classes that derive from a base class
        /// </summary>
        /// <param name="baseClassName"></param>
        public unsafe vector<const ReflectedClass *> GetDerivedClasses(string baseClassName)
        {
            return InternalCalls.BehaviorContextReflector_GetDerivedClasses(/* this pointer */, baseClassName);
        }

        /// <summary>
        /// Get classes that belong to a specific gem
        /// </summary>
        /// <param name="gemName"></param>
        /// <param name="includeDeprecated"></param>
        public unsafe vector<const ReflectedClass *> GetClassesByGem(string gemName, bool includeDeprecated)
        {
            return InternalCalls.BehaviorContextReflector_GetClassesByGem(/* this pointer */, gemName, includeDeprecated);
        }

        /// <summary>
        /// Get EBuses that belong to a specific gem
        /// </summary>
        /// <param name="gemName"></param>
        public unsafe vector<const ReflectedEBus *> GetEBusesByGem(string gemName)
        {
            return InternalCalls.BehaviorContextReflector_GetEBusesByGem(/* this pointer */, gemName);
        }

        /// <summary>
        /// Get all unique gem names that have reflected types
        /// </summary>
        public unsafe string> GetSourceGemNames()
        {
            return InternalCalls.BehaviorContextReflector_GetSourceGemNames(/* this pointer */);
        }

        /// <summary>
        /// Group all classes by their source gem
        /// </summary>
        public unsafe vector<const ReflectedClass *>> GetClassesGroupedByGem()
        {
            return InternalCalls.BehaviorContextReflector_GetClassesGroupedByGem(/* this pointer */);
        }

        /// <summary>
        /// Group all EBuses by their source gem
        /// </summary>
        public unsafe vector<const ReflectedEBus *>> GetEBusesGroupedByGem()
        {
            return InternalCalls.BehaviorContextReflector_GetEBusesGroupedByGem(/* this pointer */);
        }

        /// <summary>
        /// Set the gem name for a class (used by GemDependencyResolver)
        /// </summary>
        /// <param name="className"></param>
        /// <param name="gemName"></param>
        public unsafe void SetClassGemSource(string className, string gemName)
        {
            InternalCalls.BehaviorContextReflector_SetClassGemSource(/* this pointer */, className, gemName);
        }

        /// <summary>
        /// Set the gem name for an EBus (used by GemDependencyResolver)
        /// </summary>
        /// <param name="ebusName"></param>
        /// <param name="gemName"></param>
        public unsafe void SetEBusGemSource(string ebusName, string gemName)
        {
            InternalCalls.BehaviorContextReflector_SetEBusGemSource(/* this pointer */, ebusName, gemName);
        }

        public unsafe nuint GetClassCount()
        {
            return InternalCalls.BehaviorContextReflector_GetClassCount(/* this pointer */);
        }

        public unsafe nuint GetEBusCount()
        {
            return InternalCalls.BehaviorContextReflector_GetEBusCount(/* this pointer */);
        }

        public unsafe nuint GetGlobalMethodCount()
        {
            return InternalCalls.BehaviorContextReflector_GetGlobalMethodCount(/* this pointer */);
        }

        public unsafe nuint GetGlobalPropertyCount()
        {
            return InternalCalls.BehaviorContextReflector_GetGlobalPropertyCount(/* this pointer */);
        }

    }
}
