/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:51

using System;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Result of host initialization
    /// </summary>
    public enum CoralHostStatus
    {
        Success = 0,
        NotInitialized = 1,
        CoralManagedNotFound = 2,
        CoralInitError = 3,
        DotNetNotFound = 4,
        AssemblyLoadFailed = 5,
        AlreadyInitialized = 6
    }
}
