/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Configuration for initializing the Coral host
    /// </summary>
    public class CoralHostConfig
    {
        public string coralDirectory { get; set; }

        public string userAssemblyPath { get; set; }

        public string coreApiAssemblyPath { get; set; }

        public bool enableHotReload { get; set; }

    }
}
