/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// CSharpScriptComponent - Allows attaching C# scripts to O3DE entities
    /// </summary>
    public class CSharpScriptComponent
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.CSharpScriptComponent_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.CSharpScriptComponent_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.CSharpScriptComponent_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.CSharpScriptComponent_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.CSharpScriptComponent_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.CSharpScriptComponent_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.CSharpScriptComponent_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.CSharpScriptComponent_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.CSharpScriptComponent_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.CSharpScriptComponent_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.CSharpScriptComponent_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.CSharpScriptComponent_RTTI_AddressOf(/* this pointer */, id);
        }

        public static unsafe IntPtr CreateDescriptor()
        {
            return InternalCalls.CSharpScriptComponent_CreateDescriptor();
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.CSharpScriptComponent_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.CSharpScriptComponent_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.CSharpScriptComponent_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.CSharpScriptComponent_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.CSharpScriptComponent_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.CSharpScriptComponent_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.CSharpScriptComponent_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.CSharpScriptComponent_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.CSharpScriptComponent_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.CSharpScriptComponent_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.CSharpScriptComponent_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.CSharpScriptComponent_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.CSharpScriptComponent_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.CSharpScriptComponent_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.CSharpScriptComponent_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.CSharpScriptComponent_operator delete[](/* this pointer */, p, size, align);
        }

        public static unsafe void Reflect(IntPtr context)
        {
            InternalCalls.CSharpScriptComponent_Reflect(context);
        }

        public static unsafe void GetProvidedServices(DependencyArrayType provided)
        {
            InternalCalls.CSharpScriptComponent_GetProvidedServices(provided);
        }

        public static unsafe void GetIncompatibleServices(DependencyArrayType incompatible)
        {
            InternalCalls.CSharpScriptComponent_GetIncompatibleServices(incompatible);
        }

        public static unsafe void GetRequiredServices(DependencyArrayType required)
        {
            InternalCalls.CSharpScriptComponent_GetRequiredServices(required);
        }

        public static unsafe void GetDependentServices(DependencyArrayType dependent)
        {
            InternalCalls.CSharpScriptComponent_GetDependentServices(dependent);
        }

        public unsafe void SetConfiguration(CSharpScriptComponentConfig config)
        {
            InternalCalls.CSharpScriptComponent_SetConfiguration(/* this pointer */, config);
        }

        public unsafe CSharpScriptComponentConfig GetConfiguration()
        {
            return InternalCalls.CSharpScriptComponent_GetConfiguration(/* this pointer */);
        }

        /// <summary>
        /// Check if the managed script instance is valid and ready
        /// </summary>
        public unsafe bool IsScriptValid()
        {
            return InternalCalls.CSharpScriptComponent_IsScriptValid(/* this pointer */);
        }

        /// <summary>
        /// Reload the script (creates a new instance) Useful for hot-reload scenarios
        /// </summary>
        public unsafe void ReloadScript()
        {
            InternalCalls.CSharpScriptComponent_ReloadScript(/* this pointer */);
        }

    }
}
