/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:51

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Property handler for C# script class selection
    /// </summary>
    public class CSharpScriptClassPropertyHandler
    {
        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.CSharpScriptClassPropertyHandler_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.CSharpScriptClassPropertyHandler_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.CSharpScriptClassPropertyHandler_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.CSharpScriptClassPropertyHandler_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.CSharpScriptClassPropertyHandler_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.CSharpScriptClassPropertyHandler_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.CSharpScriptClassPropertyHandler_operator delete[](/* this pointer */, p, size, align);
        }

        public unsafe u32 GetHandlerName()
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_GetHandlerName(/* this pointer */);
        }

        public unsafe IntPtr CreateGUI(IntPtr parent)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_CreateGUI(/* this pointer */, parent);
        }

        public unsafe void ConsumeAttribute(IntPtr widget, u32 attrib, IntPtr attrValue, IntPtr debugName)
        {
            InternalCalls.CSharpScriptClassPropertyHandler_ConsumeAttribute(/* this pointer */, widget, attrib, attrValue, debugName);
        }

        public unsafe void WriteGUIValuesIntoProperty(nuint index, IntPtr GUI, int instance, IntPtr node)
        {
            InternalCalls.CSharpScriptClassPropertyHandler_WriteGUIValuesIntoProperty(/* this pointer */, index, GUI, instance, node);
        }

        public unsafe bool ReadValuesIntoGUI(nuint index, IntPtr GUI, int instance, IntPtr node)
        {
            return InternalCalls.CSharpScriptClassPropertyHandler_ReadValuesIntoGUI(/* this pointer */, index, GUI, instance, node);
        }

    }
}
