/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// EBus for communication between C++ editor components and Python editor tools
    /// </summary>
    public class CSharpEditorToolsRequests
    {
        /// <summary>
        /// Get all available C# script classes
        /// </summary>
        /// <param name="scriptsOnly"></param>
        public unsafe vector<ScriptClassInfo> GetAvailableScriptClasses(bool scriptsOnly)
        {
            return InternalCalls.CSharpEditorToolsRequests_GetAvailableScriptClasses(/* this pointer */, scriptsOnly);
        }

        /// <summary>
        /// Get just the class names (for dropdown population)
        /// </summary>
        /// <param name="scriptsOnly"></param>
        public unsafe string> GetScriptClassNames(bool scriptsOnly)
        {
            return InternalCalls.CSharpEditorToolsRequests_GetScriptClassNames(/* this pointer */, scriptsOnly);
        }

        /// <summary>
        /// Validate a script class name
        /// </summary>
        /// <param name="className"></param>
        public unsafe ScriptValidationResult ValidateScriptClass(string className)
        {
            return InternalCalls.CSharpEditorToolsRequests_ValidateScriptClass(/* this pointer */, className);
        }

        /// <summary>
        /// Open the script class picker dialog
        /// </summary>
        /// <param name="currentClass"></param>
        public unsafe string OpenScriptPicker(string currentClass)
        {
            return InternalCalls.CSharpEditorToolsRequests_OpenScriptPicker(/* this pointer */, currentClass);
        }

        /// <summary>
        /// Open the create new script dialog
        /// </summary>
        /// <param name="defaultName"></param>
        /// <param name="defaultNamespace"></param>
        public unsafe string CreateNewScript(string defaultName, string defaultNamespace)
        {
            return InternalCalls.CSharpEditorToolsRequests_CreateNewScript(/* this pointer */, defaultName, defaultNamespace);
        }

        /// <summary>
        /// Open a script file in the default IDE
        /// </summary>
        /// <param name="className"></param>
        public unsafe bool OpenScriptInEditor(string className)
        {
            return InternalCalls.CSharpEditorToolsRequests_OpenScriptInEditor(/* this pointer */, className);
        }

        /// <summary>
        /// Invalidate the script class cache (force refresh on next query)
        /// </summary>
        public unsafe void InvalidateCache()
        {
            InternalCalls.CSharpEditorToolsRequests_InvalidateCache(/* this pointer */);
        }

        /// <summary>
        /// Add a class to the recent classes list
        /// </summary>
        /// <param name="className"></param>
        public unsafe void AddToRecentClasses(string className)
        {
            InternalCalls.CSharpEditorToolsRequests_AddToRecentClasses(/* this pointer */, className);
        }

    }
}
