/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:51

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Editor-time version of the CSharpScriptComponent
    /// </summary>
    public class EditorCSharpScriptComponent
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.EditorCSharpScriptComponent_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.EditorCSharpScriptComponent_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.EditorCSharpScriptComponent_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.EditorCSharpScriptComponent_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.EditorCSharpScriptComponent_RTTI_AddressOf(/* this pointer */, id);
        }

        public static unsafe IntPtr CreateDescriptor()
        {
            return InternalCalls.EditorCSharpScriptComponent_CreateDescriptor();
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.EditorCSharpScriptComponent_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.EditorCSharpScriptComponent_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.EditorCSharpScriptComponent_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.EditorCSharpScriptComponent_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.EditorCSharpScriptComponent_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.EditorCSharpScriptComponent_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.EditorCSharpScriptComponent_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.EditorCSharpScriptComponent_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.EditorCSharpScriptComponent_operator delete[](/* this pointer */, p, size, align);
        }

        public static unsafe void Reflect(IntPtr context)
        {
            InternalCalls.EditorCSharpScriptComponent_Reflect(context);
        }

        public static unsafe void GetProvidedServices(DependencyArrayType provided)
        {
            InternalCalls.EditorCSharpScriptComponent_GetProvidedServices(provided);
        }

        public static unsafe void GetIncompatibleServices(DependencyArrayType incompatible)
        {
            InternalCalls.EditorCSharpScriptComponent_GetIncompatibleServices(incompatible);
        }

        public static unsafe void GetRequiredServices(DependencyArrayType required)
        {
            InternalCalls.EditorCSharpScriptComponent_GetRequiredServices(required);
        }

        public static unsafe void GetDependentServices(DependencyArrayType dependent)
        {
            InternalCalls.EditorCSharpScriptComponent_GetDependentServices(dependent);
        }

        public unsafe void BuildGameEntity(IntPtr gameEntity)
        {
            InternalCalls.EditorCSharpScriptComponent_BuildGameEntity(/* this pointer */, gameEntity);
        }

        public unsafe void SetConfiguration(CSharpScriptComponentConfig config)
        {
            InternalCalls.EditorCSharpScriptComponent_SetConfiguration(/* this pointer */, config);
        }

        public unsafe CSharpScriptComponentConfig GetConfiguration()
        {
            return InternalCalls.EditorCSharpScriptComponent_GetConfiguration(/* this pointer */);
        }

        /// <summary>
        /// Validate the current script class
        /// </summary>
        public unsafe void ValidateScript()
        {
            InternalCalls.EditorCSharpScriptComponent_ValidateScript(/* this pointer */);
        }

        /// <summary>
        /// Opens the script browser dialog
        /// </summary>
        public unsafe uint OnBrowseScript()
        {
            return InternalCalls.EditorCSharpScriptComponent_OnBrowseScript(/* this pointer */);
        }

        /// <summary>
        /// Opens the create new script dialog
        /// </summary>
        public unsafe uint OnCreateScript()
        {
            return InternalCalls.EditorCSharpScriptComponent_OnCreateScript(/* this pointer */);
        }

        /// <summary>
        /// Opens the script in the default IDE
        /// </summary>
        public unsafe uint OnEditScript()
        {
            return InternalCalls.EditorCSharpScriptComponent_OnEditScript(/* this pointer */);
        }

        /// <summary>
        /// Callback when script class name changes
        /// </summary>
        public unsafe uint OnScriptClassNameChanged()
        {
            return InternalCalls.EditorCSharpScriptComponent_OnScriptClassNameChanged(/* this pointer */);
        }

    }
}
