/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// GenericDispatcher - Enables C# to invoke any reflected BehaviorContext method
    /// </summary>
    public class GenericDispatcher
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.GenericDispatcher_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.GenericDispatcher_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.GenericDispatcher_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.GenericDispatcher_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.GenericDispatcher_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.GenericDispatcher_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.GenericDispatcher_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.GenericDispatcher_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.GenericDispatcher_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.GenericDispatcher_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.GenericDispatcher_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.GenericDispatcher_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.GenericDispatcher_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.GenericDispatcher_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.GenericDispatcher_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.GenericDispatcher_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.GenericDispatcher_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.GenericDispatcher_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.GenericDispatcher_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.GenericDispatcher_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.GenericDispatcher_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.GenericDispatcher_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.GenericDispatcher_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.GenericDispatcher_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.GenericDispatcher_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.GenericDispatcher_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.GenericDispatcher_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.GenericDispatcher_operator delete[](/* this pointer */, p, size, align);
        }

        /// <summary>
        /// Initialize the dispatcher with the reflector
        /// </summary>
        /// <param name="reflector"></param>
        public unsafe void Initialize(IntPtr reflector)
        {
            InternalCalls.GenericDispatcher_Initialize(/* this pointer */, reflector);
        }

        /// <summary>
        /// Shutdown and release resources
        /// </summary>
        public unsafe void Shutdown()
        {
            InternalCalls.GenericDispatcher_Shutdown(/* this pointer */);
        }

        /// <summary>
        /// Invoke a static method on a class
        /// </summary>
        /// <param name="className"></param>
        /// <param name="methodName"></param>
        /// <param name="arguments"></param>
        public unsafe DispatchResult InvokeStaticMethod(string className, string methodName, int arguments)
        {
            return InternalCalls.GenericDispatcher_InvokeStaticMethod(/* this pointer */, className, methodName, arguments);
        }

        /// <summary>
        /// Invoke an instance method on an object
        /// </summary>
        /// <param name="className"></param>
        /// <param name="methodName"></param>
        /// <param name="instanceHandle"></param>
        /// <param name="arguments"></param>
        public unsafe DispatchResult InvokeInstanceMethod(string className, string methodName, IntPtr instanceHandle, int arguments)
        {
            return InternalCalls.GenericDispatcher_InvokeInstanceMethod(/* this pointer */, className, methodName, instanceHandle, arguments);
        }

        /// <summary>
        /// Invoke a global method (not part of any class)
        /// </summary>
        /// <param name="methodName"></param>
        /// <param name="arguments"></param>
        public unsafe DispatchResult InvokeGlobalMethod(string methodName, int arguments)
        {
            return InternalCalls.GenericDispatcher_InvokeGlobalMethod(/* this pointer */, methodName, arguments);
        }

        /// <summary>
        /// Get a property value from an object
        /// </summary>
        /// <param name="className"></param>
        /// <param name="propertyName"></param>
        /// <param name="instanceHandle"></param>
        public unsafe DispatchResult GetProperty(string className, string propertyName, IntPtr instanceHandle)
        {
            return InternalCalls.GenericDispatcher_GetProperty(/* this pointer */, className, propertyName, instanceHandle);
        }

        /// <summary>
        /// Set a property value on an object
        /// </summary>
        /// <param name="className"></param>
        /// <param name="propertyName"></param>
        /// <param name="instanceHandle"></param>
        /// <param name="value"></param>
        public unsafe DispatchResult SetProperty(string className, string propertyName, IntPtr instanceHandle, MarshalledValue value)
        {
            return InternalCalls.GenericDispatcher_SetProperty(/* this pointer */, className, propertyName, instanceHandle, value);
        }

        /// <summary>
        /// Get a global property value
        /// </summary>
        /// <param name="propertyName"></param>
        public unsafe DispatchResult GetGlobalProperty(string propertyName)
        {
            return InternalCalls.GenericDispatcher_GetGlobalProperty(/* this pointer */, propertyName);
        }

        /// <summary>
        /// Set a global property value
        /// </summary>
        /// <param name="propertyName"></param>
        /// <param name="value"></param>
        public unsafe DispatchResult SetGlobalProperty(string propertyName, MarshalledValue value)
        {
            return InternalCalls.GenericDispatcher_SetGlobalProperty(/* this pointer */, propertyName, value);
        }

        /// <summary>
        /// Broadcast an event on an EBus
        /// </summary>
        /// <param name="busName"></param>
        /// <param name="eventName"></param>
        /// <param name="arguments"></param>
        public unsafe DispatchResult BroadcastEBusEvent(string busName, string eventName, int arguments)
        {
            return InternalCalls.GenericDispatcher_BroadcastEBusEvent(/* this pointer */, busName, eventName, arguments);
        }

        /// <summary>
        /// Send an event to a specific address on an EBus
        /// </summary>
        /// <param name="busName"></param>
        /// <param name="eventName"></param>
        /// <param name="address"></param>
        /// <param name="arguments"></param>
        public unsafe DispatchResult SendEBusEvent(string busName, string eventName, MarshalledValue address, int arguments)
        {
            return InternalCalls.GenericDispatcher_SendEBusEvent(/* this pointer */, busName, eventName, address, arguments);
        }

        /// <summary>
        /// Create an instance of a reflected class
        /// </summary>
        /// <param name="className"></param>
        /// <param name="constructorArgs"></param>
        public unsafe DispatchResult CreateInstance(string className, int constructorArgs)
        {
            return InternalCalls.GenericDispatcher_CreateInstance(/* this pointer */, className, constructorArgs);
        }

        /// <summary>
        /// Destroy an instance of a reflected class
        /// </summary>
        /// <param name="className"></param>
        /// <param name="instanceHandle"></param>
        public unsafe DispatchResult DestroyInstance(string className, IntPtr instanceHandle)
        {
            return InternalCalls.GenericDispatcher_DestroyInstance(/* this pointer */, className, instanceHandle);
        }

        /// <summary>
        /// Register all generic dispatcher internal calls with a Coral assembly These are the C# -> C++ entry points
        /// </summary>
        /// <param name="assembly"></param>
        public static unsafe void RegisterInternalCalls(IntPtr assembly)
        {
            InternalCalls.GenericDispatcher_RegisterInternalCalls(assembly);
        }

        /// <summary>
        /// Get the reflector (for internal calls access)
        /// </summary>
        public unsafe IntPtr GetReflector()
        {
            return InternalCalls.GenericDispatcher_GetReflector(/* this pointer */);
        }

    }
}
