/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Interface for the Coral Host Manager - allows other systems to interact with C# scripting
    /// </summary>
    public class ICoralHostManager
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.ICoralHostManager_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.ICoralHostManager_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.ICoralHostManager_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.ICoralHostManager_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.ICoralHostManager_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.ICoralHostManager_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.ICoralHostManager_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.ICoralHostManager_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.ICoralHostManager_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.ICoralHostManager_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.ICoralHostManager_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.ICoralHostManager_RTTI_AddressOf(/* this pointer */, id);
        }

        /// <summary>
        /// Initialize the .NET runtime and Coral host
        /// </summary>
        /// <param name="config"></param>
        public unsafe CoralHostStatus Initialize(CoralHostConfig config)
        {
            return InternalCalls.ICoralHostManager_Initialize(/* this pointer */, config);
        }

        /// <summary>
        /// Shutdown the .NET runtime and release all resources
        /// </summary>
        public unsafe void Shutdown()
        {
            InternalCalls.ICoralHostManager_Shutdown(/* this pointer */);
        }

        /// <summary>
        /// Check if the host is initialized and ready
        /// </summary>
        public unsafe bool IsInitialized()
        {
            return InternalCalls.ICoralHostManager_IsInitialized(/* this pointer */);
        }

        /// <summary>
        /// Load a managed assembly from disk
        /// </summary>
        /// <param name="assemblyPath"></param>
        public unsafe IntPtr LoadAssembly(string assemblyPath)
        {
            return InternalCalls.ICoralHostManager_LoadAssembly(/* this pointer */, assemblyPath);
        }

        /// <summary>
        /// Reload user assemblies (for hot-reload support)
        /// </summary>
        public unsafe bool ReloadUserAssemblies()
        {
            return InternalCalls.ICoralHostManager_ReloadUserAssemblies(/* this pointer */);
        }

        /// <summary>
        /// Get a type from the core API assembly
        /// </summary>
        /// <param name="fullTypeName"></param>
        public unsafe IntPtr GetCoreType(string fullTypeName)
        {
            return InternalCalls.ICoralHostManager_GetCoreType(/* this pointer */, fullTypeName);
        }

        /// <summary>
        /// Get a type from the user assembly
        /// </summary>
        /// <param name="fullTypeName"></param>
        public unsafe IntPtr GetUserType(string fullTypeName)
        {
            return InternalCalls.ICoralHostManager_GetUserType(/* this pointer */, fullTypeName);
        }

        /// <summary>
        /// Create an instance of a managed type
        /// </summary>
        /// <param name="type"></param>
        public unsafe int CreateInstance(int type)
        {
            return InternalCalls.ICoralHostManager_CreateInstance(/* this pointer */, type);
        }

        /// <summary>
        /// Get the core API assembly (O3DE.Core.dll)
        /// </summary>
        public unsafe IntPtr GetCoreAssembly()
        {
            return InternalCalls.ICoralHostManager_GetCoreAssembly(/* this pointer */);
        }

        /// <summary>
        /// Get the user game assembly
        /// </summary>
        public unsafe IntPtr GetUserAssembly()
        {
            return InternalCalls.ICoralHostManager_GetUserAssembly(/* this pointer */);
        }

    }
}
