/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    public class InteropVector3
    {
        public float x { get; set; }

        public float y { get; set; }

        public float z { get; set; }


        public unsafe Vector3 ToAZ()
        {
            return InternalCalls.InteropVector3_ToAZ(/* this pointer */);
        }

    }
}
