/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Represents a value that can be passed between C++ and C# This is a variant type that can hold any marshallable value
    /// </summary>
    public class MarshalledValue
    {
        public MarshalType type { get; set; }

        public string stringValue { get; set; }

        public IntPtr objectHandle { get; set; }

        public string objectTypeName { get; set; }


        public static unsafe MarshalledValue FromBool(bool value)
        {
            return InternalCalls.MarshalledValue_FromBool(value);
        }

        public static unsafe MarshalledValue FromInt32(int value)
        {
            return InternalCalls.MarshalledValue_FromInt32(value);
        }

        public static unsafe MarshalledValue FromInt64(long value)
        {
            return InternalCalls.MarshalledValue_FromInt64(value);
        }

        public static unsafe MarshalledValue FromUInt64(ulong value)
        {
            return InternalCalls.MarshalledValue_FromUInt64(value);
        }

        public static unsafe MarshalledValue FromFloat(float value)
        {
            return InternalCalls.MarshalledValue_FromFloat(value);
        }

        public static unsafe MarshalledValue FromDouble(double value)
        {
            return InternalCalls.MarshalledValue_FromDouble(value);
        }

        public static unsafe MarshalledValue FromString(string value)
        {
            return InternalCalls.MarshalledValue_FromString(value);
        }

        public static unsafe MarshalledValue FromVector3(float x, float y, float z)
        {
            return InternalCalls.MarshalledValue_FromVector3(x, y, z);
        }

        public static unsafe MarshalledValue FromQuaternion(float x, float y, float z, float w)
        {
            return InternalCalls.MarshalledValue_FromQuaternion(x, y, z, w);
        }

        public static unsafe MarshalledValue FromEntityId(u64 entityId)
        {
            return InternalCalls.MarshalledValue_FromEntityId(entityId);
        }

        public static unsafe MarshalledValue FromObject(IntPtr handle, string typeName)
        {
            return InternalCalls.MarshalledValue_FromObject(handle, typeName);
        }

    }
}
