/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// O3DESharpSystemComponent - Core system component for C# scripting support
    /// </summary>
    public class O3DESharpSystemComponent
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.O3DESharpSystemComponent_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.O3DESharpSystemComponent_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpSystemComponent_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_AddressOf(/* this pointer */, id);
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpSystemComponent_RTTI_EnumHierarchy(cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.O3DESharpSystemComponent_RTTI_TypeName();
        }

        public static unsafe IntPtr CreateDescriptor()
        {
            return InternalCalls.O3DESharpSystemComponent_CreateDescriptor();
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.O3DESharpSystemComponent_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.O3DESharpSystemComponent_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.O3DESharpSystemComponent_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.O3DESharpSystemComponent_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.O3DESharpSystemComponent_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.O3DESharpSystemComponent_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.O3DESharpSystemComponent_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.O3DESharpSystemComponent_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.O3DESharpSystemComponent_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.O3DESharpSystemComponent_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.O3DESharpSystemComponent_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.O3DESharpSystemComponent_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t , align_val_t )
        {
            return InternalCalls.O3DESharpSystemComponent_operator new[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.O3DESharpSystemComponent_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.O3DESharpSystemComponent_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.O3DESharpSystemComponent_operator delete[](/* this pointer */, p, size, align);
        }

        public static unsafe void Reflect(IntPtr context)
        {
            InternalCalls.O3DESharpSystemComponent_Reflect(context);
        }

        public static unsafe void GetProvidedServices(DependencyArrayType provided)
        {
            InternalCalls.O3DESharpSystemComponent_GetProvidedServices(provided);
        }

        public static unsafe void GetIncompatibleServices(DependencyArrayType incompatible)
        {
            InternalCalls.O3DESharpSystemComponent_GetIncompatibleServices(incompatible);
        }

        public static unsafe void GetRequiredServices(DependencyArrayType required)
        {
            InternalCalls.O3DESharpSystemComponent_GetRequiredServices(required);
        }

        public static unsafe void GetDependentServices(DependencyArrayType dependent)
        {
            InternalCalls.O3DESharpSystemComponent_GetDependentServices(dependent);
        }

    }
}
