/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    public class O3DESharpFeatureProcessorInterface
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpFeatureProcessorInterface_RTTI_AddressOf(/* this pointer */, id);
        }

    }
}
