/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    public class O3DESharpComponentController
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.O3DESharpComponentController_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.O3DESharpComponentController_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.O3DESharpComponentController_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.O3DESharpComponentController_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.O3DESharpComponentController_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpComponentController_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.O3DESharpComponentController_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.O3DESharpComponentController_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.O3DESharpComponentController_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpComponentController_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpComponentController_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpComponentController_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.O3DESharpComponentController_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.O3DESharpComponentController_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.O3DESharpComponentController_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.O3DESharpComponentController_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.O3DESharpComponentController_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.O3DESharpComponentController_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.O3DESharpComponentController_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.O3DESharpComponentController_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.O3DESharpComponentController_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.O3DESharpComponentController_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.O3DESharpComponentController_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.O3DESharpComponentController_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.O3DESharpComponentController_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.O3DESharpComponentController_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.O3DESharpComponentController_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.O3DESharpComponentController_operator delete[](/* this pointer */, p, size, align);
        }

        public static unsafe void Reflect(IntPtr context)
        {
            InternalCalls.O3DESharpComponentController_Reflect(context);
        }

        public static unsafe void GetDependentServices(DependencyArrayType dependent)
        {
            InternalCalls.O3DESharpComponentController_GetDependentServices(dependent);
        }

        public static unsafe void GetProvidedServices(DependencyArrayType provided)
        {
            InternalCalls.O3DESharpComponentController_GetProvidedServices(provided);
        }

        public static unsafe void GetIncompatibleServices(DependencyArrayType incompatible)
        {
            InternalCalls.O3DESharpComponentController_GetIncompatibleServices(incompatible);
        }

        public static unsafe void GetRequiredServices(DependencyArrayType required)
        {
            InternalCalls.O3DESharpComponentController_GetRequiredServices(required);
        }

        public unsafe void Activate(ulong entityId)
        {
            InternalCalls.O3DESharpComponentController_Activate(/* this pointer */, entityId);
        }

        public unsafe void Deactivate()
        {
            InternalCalls.O3DESharpComponentController_Deactivate(/* this pointer */);
        }

        public unsafe void SetConfiguration(O3DESharpComponentConfig config)
        {
            InternalCalls.O3DESharpComponentController_SetConfiguration(/* this pointer */, config);
        }

        public unsafe O3DESharpComponentConfig GetConfiguration()
        {
            return InternalCalls.O3DESharpComponentController_GetConfiguration(/* this pointer */);
        }

    }
}
