/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// O3DESharpRequests - Interface for C# scripting system operations
    /// </summary>
    public class O3DESharpRequests
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.O3DESharpRequests_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.O3DESharpRequests_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.O3DESharpRequests_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.O3DESharpRequests_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.O3DESharpRequests_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpRequests_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.O3DESharpRequests_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.O3DESharpRequests_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.O3DESharpRequests_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.O3DESharpRequests_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpRequests_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.O3DESharpRequests_RTTI_AddressOf(/* this pointer */, id);
        }

        /// <summary>
        /// Check if the Coral .NET host is initialized and ready
        /// </summary>
        public unsafe bool IsCoralHostInitialized()
        {
            return InternalCalls.O3DESharpRequests_IsCoralHostInitialized(/* this pointer */);
        }

        /// <summary>
        /// Get the status message of the Coral host
        /// </summary>
        public unsafe string GetCoralHostStatus()
        {
            return InternalCalls.O3DESharpRequests_GetCoralHostStatus(/* this pointer */);
        }

        /// <summary>
        /// Load a C# assembly from the specified path
        /// </summary>
        /// <param name="assemblyPath"></param>
        public unsafe bool LoadAssembly(string assemblyPath)
        {
            return InternalCalls.O3DESharpRequests_LoadAssembly(/* this pointer */, assemblyPath);
        }

        /// <summary>
        /// Reload all user assemblies (triggers hot-reload)
        /// </summary>
        public unsafe bool ReloadUserAssemblies()
        {
            return InternalCalls.O3DESharpRequests_ReloadUserAssemblies(/* this pointer */);
        }

        /// <summary>
        /// Check if hot-reload is enabled
        /// </summary>
        public unsafe bool IsHotReloadEnabled()
        {
            return InternalCalls.O3DESharpRequests_IsHotReloadEnabled(/* this pointer */);
        }

        /// <summary>
        /// Check if a C# type exists in the loaded assemblies
        /// </summary>
        /// <param name="fullTypeName"></param>
        public unsafe bool TypeExists(string fullTypeName)
        {
            return InternalCalls.O3DESharpRequests_TypeExists(/* this pointer */, fullTypeName);
        }

        /// <summary>
        /// Get a list of all script types (classes inheriting from ScriptComponent)
        /// </summary>
        public unsafe string> GetAvailableScriptTypes()
        {
            return InternalCalls.O3DESharpRequests_GetAvailableScriptTypes(/* this pointer */);
        }

        /// <summary>
        /// Get the path to the Coral directory
        /// </summary>
        public unsafe string GetCoralDirectory()
        {
            return InternalCalls.O3DESharpRequests_GetCoralDirectory(/* this pointer */);
        }

        /// <summary>
        /// Get the path to the core API assembly (O3DE.Core.dll)
        /// </summary>
        public unsafe string GetCoreAssemblyPath()
        {
            return InternalCalls.O3DESharpRequests_GetCoreAssemblyPath(/* this pointer */);
        }

        /// <summary>
        /// Get the path to the user game assembly
        /// </summary>
        public unsafe string GetUserAssemblyPath()
        {
            return InternalCalls.O3DESharpRequests_GetUserAssemblyPath(/* this pointer */);
        }

    }
}
