/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Result of a reflection data export operation
    /// </summary>
    public class ReflectionExportResult
    {
        public bool success { get; set; }

        public string errorMessage { get; set; }

        public string jsonData { get; set; }

        public nuint classesExported { get; set; }

        public nuint ebusesExported { get; set; }

        public nuint globalMethodsExported { get; set; }

        public nuint globalPropertiesExported { get; set; }

        public Path outputPath { get; set; }


        public static unsafe ReflectionExportResult Success(string json)
        {
            return InternalCalls.ReflectionExportResult_Success(json);
        }

        public static unsafe ReflectionExportResult Error(string message)
        {
            return InternalCalls.ReflectionExportResult_Error(message);
        }

    }
}
