/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// ReflectionDataExporter - Exports BehaviorContext reflection data to JSON
    /// </summary>
    public class ReflectionDataExporter
    {
        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.ReflectionDataExporter_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.ReflectionDataExporter_TYPEINFO_Uuid();
        }

        public unsafe TypeId RTTI_GetType()
        {
            return InternalCalls.ReflectionDataExporter_RTTI_GetType(/* this pointer */);
        }

        public unsafe IntPtr RTTI_GetTypeName()
        {
            return InternalCalls.ReflectionDataExporter_RTTI_GetTypeName(/* this pointer */);
        }

        public unsafe bool RTTI_IsTypeOf(TypeId typeId)
        {
            return InternalCalls.ReflectionDataExporter_RTTI_IsTypeOf(/* this pointer */, typeId);
        }

        public unsafe void RTTI_EnumTypes(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.ReflectionDataExporter_RTTI_EnumTypes(/* this pointer */, cb, userData);
        }

        public static unsafe TypeId RTTI_Type()
        {
            return InternalCalls.ReflectionDataExporter_RTTI_Type();
        }

        public static unsafe IntPtr RTTI_TypeName()
        {
            return InternalCalls.ReflectionDataExporter_RTTI_TypeName();
        }

        public static unsafe bool RTTI_IsContainType(TypeId id)
        {
            return InternalCalls.ReflectionDataExporter_RTTI_IsContainType(id);
        }

        public static unsafe void RTTI_EnumHierarchy(RTTI_EnumCallback cb, IntPtr userData)
        {
            InternalCalls.ReflectionDataExporter_RTTI_EnumHierarchy(cb, userData);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.ReflectionDataExporter_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr RTTI_AddressOf(TypeId id)
        {
            return InternalCalls.ReflectionDataExporter_RTTI_AddressOf(/* this pointer */, id);
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.ReflectionDataExporter_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.ReflectionDataExporter_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.ReflectionDataExporter_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.ReflectionDataExporter_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.ReflectionDataExporter_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.ReflectionDataExporter_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.ReflectionDataExporter_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.ReflectionDataExporter_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.ReflectionDataExporter_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.ReflectionDataExporter_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.ReflectionDataExporter_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.ReflectionDataExporter_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.ReflectionDataExporter_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.ReflectionDataExporter_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.ReflectionDataExporter_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.ReflectionDataExporter_operator delete[](/* this pointer */, p, size, align);
        }

        /// <summary>
        /// Export reflection data to JSON
        /// </summary>
        /// <param name="reflector"></param>
        /// <param name="config"></param>
        public unsafe ReflectionExportResult Export(BehaviorContextReflector reflector, ReflectionExportConfig config)
        {
            return InternalCalls.ReflectionDataExporter_Export(/* this pointer */, reflector, config);
        }

        /// <summary>
        /// Export reflection data directly from a BehaviorContext This is a convenience method that creates a temporary reflector
        /// </summary>
        /// <param name="context"></param>
        /// <param name="config"></param>
        public unsafe ReflectionExportResult ExportFromContext(IntPtr context, ReflectionExportConfig config)
        {
            return InternalCalls.ReflectionDataExporter_ExportFromContext(/* this pointer */, context, config);
        }

        /// <summary>
        /// Export to a JSON string (no file output)
        /// </summary>
        /// <param name="reflector"></param>
        /// <param name="prettyPrint"></param>
        public unsafe string ExportToString(BehaviorContextReflector reflector, bool prettyPrint)
        {
            return InternalCalls.ReflectionDataExporter_ExportToString(/* this pointer */, reflector, prettyPrint);
        }

        /// <summary>
        /// Export to a file
        /// </summary>
        /// <param name="reflector"></param>
        /// <param name="outputPath"></param>
        /// <param name="config"></param>
        public unsafe ReflectionExportResult ExportToFile(BehaviorContextReflector reflector, Path outputPath, ReflectionExportConfig config)
        {
            return InternalCalls.ReflectionDataExporter_ExportToFile(/* this pointer */, reflector, outputPath, config);
        }

    }
}
