/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Represents a parameter in a reflected method
    /// </summary>
    public class ReflectedParameter
    {
        public string name { get; set; }

        public Guid typeId { get; set; }

        public string typeName { get; set; }

        public bool isPointer { get; set; }

        public bool isReference { get; set; }

        public bool isConst { get; set; }

        public MarshalType marshalType { get; set; }

    }
}
