/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Represents a reflected method from BehaviorContext
    /// </summary>
    public class ReflectedMethod
    {
        public string name { get; set; }

        public string className { get; set; }

        public bool isStatic { get; set; }

        public bool isConst { get; set; }

        public ReflectedParameter returnType { get; set; }

        public vector<ReflectedParameter> parameters { get; set; }

        public IntPtr behaviorMethod { get; set; }

        public string description { get; set; }

        public string category { get; set; }

        public bool isDeprecated { get; set; }

        public string deprecationMessage { get; set; }

    }
}
