/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// EBus interface for requesting reflection data export This allows scripts and editor tools to trigger export operations
    /// </summary>
    public class ReflectionDataExportRequests
    {
        /// <summary>
        /// Export reflection data to a JSON file
        /// </summary>
        /// <param name="outputPath"></param>
        public unsafe bool ExportReflectionData(string outputPath)
        {
            return InternalCalls.ReflectionDataExportRequests_ExportReflectionData(/* this pointer */, outputPath);
        }

        /// <summary>
        /// Get reflection data as a JSON string
        /// </summary>
        public unsafe string GetReflectionDataJson()
        {
            return InternalCalls.ReflectionDataExportRequests_GetReflectionDataJson(/* this pointer */);
        }

        /// <summary>
        /// Get reflection data for a specific category
        /// </summary>
        /// <param name="category"></param>
        public unsafe string GetReflectionDataForCategory(string category)
        {
            return InternalCalls.ReflectionDataExportRequests_GetReflectionDataForCategory(/* this pointer */, category);
        }

        /// <summary>
        /// Get a list of all reflected class names
        /// </summary>
        public unsafe string> GetReflectedClassNames()
        {
            return InternalCalls.ReflectionDataExportRequests_GetReflectedClassNames(/* this pointer */);
        }

        /// <summary>
        /// Get a list of all reflected EBus names
        /// </summary>
        public unsafe string> GetReflectedEBusNames()
        {
            return InternalCalls.ReflectionDataExportRequests_GetReflectedEBusNames(/* this pointer */);
        }

        /// <summary>
        /// Get all unique categories in the reflection data
        /// </summary>
        public unsafe string> GetReflectedCategories()
        {
            return InternalCalls.ReflectionDataExportRequests_GetReflectedCategories(/* this pointer */);
        }

    }
}
