/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Represents a reflected class from BehaviorContext
    /// </summary>
    public class ReflectedClass
    {
        public string name { get; set; }

        public Guid typeId { get; set; }

        public string> baseClasses { get; set; }

        public vector<ReflectedMethod> methods { get; set; }

        public vector<ReflectedProperty> properties { get; set; }

        public vector<ReflectedMethod> constructors { get; set; }

        public IntPtr behaviorClass { get; set; }

        public string description { get; set; }

        public string category { get; set; }

        public bool isDeprecated { get; set; }

        public string sourceGemName { get; set; }

        public string sourceModuleName { get; set; }


        public unsafe IntPtr FindMethod(string methodName)
        {
            return InternalCalls.ReflectedClass_FindMethod(/* this pointer */, methodName);
        }

        public unsafe IntPtr FindProperty(string propertyName)
        {
            return InternalCalls.ReflectedClass_FindProperty(/* this pointer */, propertyName);
        }

    }
}
