/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Represents a reflected EBus from BehaviorContext
    /// </summary>
    public class ReflectedEBus
    {
        public string name { get; set; }

        public Guid typeId { get; set; }

        public ReflectedParameter addressType { get; set; }

        public vector<ReflectedEBusEvent> events { get; set; }

        public IntPtr behaviorEBus { get; set; }

        public string description { get; set; }

        public string category { get; set; }

        public string sourceGemName { get; set; }

        public string sourceModuleName { get; set; }

    }
}
