/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Represents a reflected property from BehaviorContext
    /// </summary>
    public class ReflectedProperty
    {
        public string name { get; set; }

        public string className { get; set; }

        public ReflectedParameter valueType { get; set; }

        public bool hasGetter { get; set; }

        public bool hasSetter { get; set; }

        public IntPtr behaviorProperty { get; set; }

        public string description { get; set; }

        public bool isDeprecated { get; set; }

    }
}
