/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// Data structure representing a C# script class with metadata
    /// </summary>
    public class ScriptClassInfo
    {
        /// <summary>
        /// Fully qualified name (Namespace.ClassName)
        /// </summary>
        public string m_fullName { get; set; }

        /// <summary>
        /// Short class name
        /// </summary>
        public string m_className { get; set; }

        /// <summary>
        /// Namespace
        /// </summary>
        public string m_namespace { get; set; }

        /// <summary>
        /// Name of the containing C# project
        /// </summary>
        public string m_projectName { get; set; }

        /// <summary>
        /// Full path to the .cs file
        /// </summary>
        public string m_filePath { get; set; }

        /// <summary>
        /// Base class name (e.g., "ScriptComponent")
        /// </summary>
        public string m_baseClass { get; set; }

        /// <summary>
        /// True if class derives from ScriptComponent
        /// </summary>
        public bool m_isScriptComponent { get; set; }

        /// <summary>
        /// True if this is a recently used class
        /// </summary>
        public bool m_isRecent { get; set; }


        public static unsafe IntPtr TYPEINFO_Name()
        {
            return InternalCalls.ScriptClassInfo_TYPEINFO_Name();
        }

        public static unsafe TypeId TYPEINFO_Uuid()
        {
            return InternalCalls.ScriptClassInfo_TYPEINFO_Uuid();
        }

        public unsafe IntPtr operator new(size_t , IntPtr p)
        {
            return InternalCalls.ScriptClassInfo_operator new(/* this pointer */, , p);
        }

        public unsafe IntPtr operator new[](size_t , IntPtr p)
        {
            return InternalCalls.ScriptClassInfo_operator new[](/* this pointer */, , p);
        }

        public unsafe void operator delete(IntPtr , IntPtr )
        {
            InternalCalls.ScriptClassInfo_operator delete(/* this pointer */, , );
        }

        public unsafe void operator delete[](IntPtr , IntPtr )
        {
            InternalCalls.ScriptClassInfo_operator delete[](/* this pointer */, , );
        }

        public unsafe IntPtr operator new(size_t size)
        {
            return InternalCalls.ScriptClassInfo_operator new(/* this pointer */, size);
        }

        public unsafe void operator delete(IntPtr p, size_t size)
        {
            InternalCalls.ScriptClassInfo_operator delete(/* this pointer */, p, size);
        }

        public unsafe IntPtr operator new[](size_t )
        {
            return InternalCalls.ScriptClassInfo_operator new[](/* this pointer */, );
        }

        public unsafe void operator delete[](IntPtr )
        {
            InternalCalls.ScriptClassInfo_operator delete[](/* this pointer */, );
        }

        public static unsafe IntPtr AZ_CLASS_ALLOCATOR_Allocate()
        {
            return InternalCalls.ScriptClassInfo_AZ_CLASS_ALLOCATOR_Allocate();
        }

        public static unsafe void AZ_CLASS_ALLOCATOR_DeAllocate(IntPtr object)
        {
            InternalCalls.ScriptClassInfo_AZ_CLASS_ALLOCATOR_DeAllocate(object);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align)
        {
            return InternalCalls.ScriptClassInfo_operator new(/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new(size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.ScriptClassInfo_operator new(/* this pointer */, size, align, );
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align)
        {
            return InternalCalls.ScriptClassInfo_operator new[](/* this pointer */, size, align);
        }

        public unsafe IntPtr operator new[](size_t size, align_val_t align, nothrow_t )
        {
            return InternalCalls.ScriptClassInfo_operator new[](/* this pointer */, size, align, );
        }

        public unsafe void operator delete(IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.ScriptClassInfo_operator delete(/* this pointer */, p, size, align);
        }

        public unsafe void operator delete[](IntPtr p, size_t size, align_val_t align)
        {
            InternalCalls.ScriptClassInfo_operator delete[](/* this pointer */, p, size, align);
        }

        public static unsafe void Reflect(IntPtr context)
        {
            InternalCalls.ScriptClassInfo_Reflect(context);
        }

    }
}
