/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by O3DESharp.BindingGenerator on 2026-02-14 12:36:50

using System;
using Coral.Managed.Interop;

namespace O3DE.O3DESharp
{
    /// <summary>
    /// ScriptBindings - Static class that registers all C++ functions exposed to C#
    /// </summary>
    public class ScriptBindings
    {
        /// <summary>
        /// Register all internal calls with the given assembly
        /// </summary>
        /// <param name="assembly"></param>
        public static unsafe void RegisterAll(IntPtr assembly)
        {
            InternalCalls.ScriptBindings_RegisterAll(assembly);
        }

    }
}
